### ISSUE TITLE
Submit button for upload file should be disabled during upload

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/OTP-Data-Entry#100]
Currently the user try to submit, but gets a validation error.

The correct functionality is that the user cannot click the submit button

**Comment by Karyum** [comment]
hmm i would say there would be no way for the user to submit while the image is being uploaded [because of the validation here](https://github.com/foundersandcoders/OTP-Data-Entry/blob/master/public/validate-event-form.js#L28-L32) but i'll disable the input :wink:

**Comment by des-des** [comment]
Its about having a polished feel, ie this is not a bug in terms of data integrity, but a bug in UX
