### ISSUE TITLE
Sprint Review meeting, 5/9/2017

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/OTP-Data-Entry#27]
What time is best for everyone? I can do anytime.

@RQ16 @des-des (@JWLD?)

**Comment by m4v15** [comment]
Just to clarify this meeting will be the handover from Reem, with the project likely being picked up by another FACNer, just so we all know where we are on it.

**Comment by RQ16** [comment]
I can meet at any point on Tuesday, but would prefer in the evening hours to have more time during the day to add to the code.

**Comment by m4v15** [comment]
6pm Naz, so 4pm London? @des-des

**Comment by des-des** [comment]
YO 4pm London time Tuesday 5th Sept confo!
