### ISSUE TITLE
Heroku details

### ISSUE THREAD

**Issue by philawsophizing** [foundersandcoders/OTP-Data-Entry#33]
What is the associated heroku account to keep it updated as we go?

@JWLD @m4v15 @RQ16

**Comment by RQ16** [comment]
data.entry.fac@gmail.com

**Comment by RQ16** [comment]
Also, typical password

**Comment by philawsophizing** [comment]
@RQ16 shukran habibi :maple_leaf:

**Comment by m4v15** [comment]
@Suuuuha lets push the latest version up on Monday
