### ISSUE TITLE
Sprint review

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/OTP-Data-Entry#36]
I think the Sprint 1.5 milestone is coming up in a couple of days. Can I join the sprint review? Tareq and Waleed are keen on an update and I want to make sure that I have a clear picture for them when I meet them next week.

**Comment by m4v15** [comment]
Yes, it will be at some point tomorrow, we will confirm later today exactly when

**Comment by m4v15** [comment]
@sofer Apologies, forgot to confirm. We are ready to do it at any point this afternoon, is there a time that is easier for you. @JWLD @philawsophizing @Suuuuha when is good for you guys (@philawsophizing only if you happen to be available, thought it would be nice!)

The only time I can't do is 5pm Israel time, best for me would probably be 3pm Israel, 1pm London

**Comment by m4v15** [comment]
@des-des as well if you're avaliable!

**Comment by Suuuuha** [comment]
I'm happy to do it anytime today
