### ISSUE TITLE
Error handling in langError.js

### ISSUE THREAD

**Issue by jwld** [foundersandcoders/OTP-Data-Entry#52]
https://github.com/foundersandcoders/OTP-Data-Entry/blob/156300117e81e3db269af7d18a8feae823fdd920/src/middleware/langError.js#L11

`res.locals.localText` won't have been set in this case, so you can't pass in a localised error message

**Comment by m4v15** [comment]
Yeah it's fixed in the next PR right - it's fine to have an English Error message here I think, as the whole error is that we don't know what language they want!

**Comment by Suuuuha** [comment]
fixed in the add and edit PR so it could be closed i guess!
