### ISSUE TITLE
add compression

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/OTP-Data-Entry#65]
it might make the app faster or something?

https://github.com/expressjs/compression

**Comment by mattlub** [comment]
does it?

**Comment by m4v15** [comment]
Well yeah I some what doubt it but actually i looked it up and there's talk of 15-20% performance increase

**Comment by Karyum** [comment]
# Thank You !

**Comment by Karyum** [comment]
@m4v15 @Suuuuha  theres a couple more ways 
http://stackabuse.com/6-easy-ways-to-speed-up-express/
