### ISSUE TITLE
Nazareth Open Tourism Platform URL change

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/OTP-Data-Entry#84]
Please Note that the base url for all API calls to the Nazareth Open Tourism Platfor has been changed to 

`https://nazareth-open-tourism-platform.herokuapp.com/api/v1/`

so any API calls must be changed appropriately.

**Comment by Karyum** [comment]
@m4v15 @Suuuuha Liwan and volunteers from Tareq needs this app so i'll take this issue on
