### ISSUE TITLE
Not enough categories

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/OTP-Data-Entry#91]
They mentioned that there should be more categories like movie, theatre, kids, workshops.

EPIC: #90

**Comment by Karyum** [comment]
I'm guessing this shouldn't be really difficult i just need to add the new categories they asked for in [ the OTP's constants file](https://github.com/foundersandcoders/open-tourism-platform/blob/master/src/models/constants.json#L31) correct?

**Comment by des-des** [comment]
I think so!

**Comment by Karyum** [comment]
closing this since https://github.com/foundersandcoders/open-tourism-platform/pull/174 was merged
