### ISSUE TITLE
Funky image url behaviour

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/OTP-Data-Entry#95]
The current functionality of dropping in a URL is not so nice. If we could integrate s3 that would be better
EPIC: #90

**Comment by Karyum** [comment]
it's more of they weren't sure where to copy the image address from, sometimes on images it says "copy image address" but it doesn't work.

What im thinking of to help in this is when they add the url to the input a preview of the image would a appear next to the input ( it would just be an img tag without an src ) what do you think @des-des ?

**Comment by des-des** [comment]
@Karyum did any suggestions come from them (the PO) on how to do this?

**Comment by Karyum** [comment]
nah not really, when i explained about we are also gonna have the ability to add the event's images from the local computer ( AWS S3 ) they seemed happy with that

**Comment by Karyum** [comment]
rel #86
